export const ActionTypes = {

    CONNECTION_SUCCESS: "CONNECTION_SUCCESS",
    CONNECTION_CLOSED: "CONNECTION_CLOSED",

    FETCH_DATA_INIT: "FETCH_DATA_INIT",
    FETCH_DATA_COMPLETE: "FETCH_DATA_COMPLETE",
    FETCH_DATA_FAILED: "FETCH_DATA_FAILED",

    FETCH_INDEX_DATA: "FETCH_INDEX_DATA",
    FETCH_EXPO_DATA: "FETCH_EXPO_DATA",

    FETCH_DATA_INIT_BANK: "FETCH_DATA_INIT_BANK",
    FETCH_DATA_COMPLETE_BANK: "FETCH_DATA_COMPLETE_BANK",
    FETCH_DATA_FAILED_BANK: "FETCH_DATA_FAILED_BANK",

    FETCH_INDEX_INIT_BANK: "FETCH_INDEX_INIT_BANK",
    FETCH_INDEX_COMPLETE_BANK: "FETCH_INDEX_COMPLETE_BANK",
    FETCH_INDEX_FAILED_BANK: "FETCH_INDEX_FAILED_BANK",

    FETCH_INDEX_INIT: "FETCH_INDEX_INIT",
    FETCH_INDEX_COMPLETE: "FETCH_INDEX_COMPLETE",
    FETCH_INDEX_FAILED: "FETCH_INDEX_FAILED",

    FETCH_TICK_DATA_INIT: "FETCH_TICK_DATA_INIT",
    FETCH_TICK_DATA_COMPLETE: "FETCH_TICK_DATA_INIT",
    FETCH_TICK_DATA_FAILED: "FETCH_TICK_DATA_INIT",

    FETCH_TICK_DATA_INIT_BANK: "FETCH_TICK_DATA_INIT_BANK",
    FETCH_TICK_DATA_COMPLETE_BANK: "FETCH_TICK_DATA_COMPLETE_BANK",
    FETCH_TICK_DATA_FAILED_BANK: "FETCH_TICK_DATA_FAILED_BANK",

    CHANGE_DURATION: "CHANGE_DURATION"
}