export const ActionTypes = {

    CONNECTION_SUCCESS: "CONNECTION_SUCCESS",

    FETCH_DATA_INIT: "FETCH_DATA_INIT",
    FETCH_DATA_COMPLETE: "FETCH_DATA_COMPLETE",
    FETCH_DATA_FAILED: "FETCH_DATA_FAILED",

    FETCH_DATA_INIT_BANK: "FETCH_DATA_INIT_BANK",
    FETCH_DATA_COMPLETE_BANK: "FETCH_DATA_COMPLETE_BANK",
    FETCH_DATA_FAILED_BANK: "FETCH_DATA_FAILED_BANK",

    FETCH_TICK_DATA_INIT: "FETCH_TICK_DATA_INIT",
    FETCH_TICK_DATA_COMPLETE: "FETCH_TICK_DATA_INIT",
    FETCH_TICK_DATA_FAILED: "FETCH_TICK_DATA_INIT",

    FETCH_TICK_DATA_INIT_BANK: "FETCH_TICK_DATA_INIT_BANK",
    FETCH_TICK_DATA_COMPLETE_BANK: "FETCH_TICK_DATA_COMPLETE_BANK",
    FETCH_TICK_DATA_FAILED_BANK: "FETCH_TICK_DATA_FAILED_BANK",
}